import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="w-full flex justify-center items-center gap-8 py-4 border-b border-gray-200 mb-8 z-50 relative">
          <Link href="/" className="font-semibold text-lg hover:underline">Home</Link>
          <Link href="/my-workouts" className="font-semibold text-lg hover:underline">My Workouts</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
